### ISSUE TITLE
load media failed 

### ISSUE THREAD

**Issue by xtyi1997** [Axel-Erfurt/Python-QT-VideoPlayer#2]
I clone this code ,but it does not work .
load media failed 
i need your help in your convenience

**Comment by Axel-Erfurt** [comment]
You mean QT5_Videoplayer ?
What is your operating system and Qt Version?

**Comment by xtyi1997** [comment]
> You mean QT5_Videoplayer ?
> What is your operating system and Qt Version?

my operating system is mac and my qt version is qt5.12.0

**Comment by Axel-Erfurt** [comment]
Can you please start it  from Terminal to see error messages.

**Comment by osamabillah** [comment]
Error while loading the video.
DirectShowPlayerService::doRender: Unresolved error code 0x80040266 (IDispatch error #102)

**Comment by Axel-Erfurt** [comment]
Your OS is Windows?

missing codecs.

Try [LAVFilters](https://github.com/Nevcairiel/LAVFilters) or the [K-lite basic codec package](https://www.codecguide.com/download_kl.htm)

**Comment by osamabillah** [comment]
yes sir

**Comment by osamabillah** [comment]
I tried it on linux(ubuntu) too
