### ISSUE TITLE
Video player not opening, only a white blank screen appears

### ISSUE THREAD

**Issue by RohitKumar2511** [Axel-Erfurt/Python-QT-VideoPlayer#3]
there are two problems with the code of yours: (!) it's opening as a **White blank page**      (!!)  Video not playing

**Comment by Axel-Erfurt** [comment]
Which file do you mean?
Please run it in the terminal and post the error message.

**Comment by RohitKumar2511** [comment]
I mean, i clone QT-VideoPlayer program and run it in IDLE but it is showing a **white screen with nothing in it**

**Comment by RohitKumar2511** [comment]
i mean when clone QT-VideoPlayer and run it in IDLE.But output of the program is only a **White screen withh no content **

**Comment by Axel-Erfurt** [comment]
I'm asking again, which File?
There is no file QT-VideoPlayer


PhononVideoPlayer.py
QT5_VideoPlayer.py
TV_LiveStream.py
VideoSchneiden.py

**Comment by RohitKumar2511** [comment]
I'm talking about QT5_VideoPlayer.py


Rohit Kumar Mahato

**Comment by Axel-Erfurt** [comment]
What is your operating system and what PyQt5 version do you have?

Usually it shows a black window.

Did you try to open a file?
Right click or press 'o'.

**Comment by RohitKumar2511** [comment]
Right now I'm using Windows 10 OS and have installed PYQT5 version.
But , sir it is showing a white screen window.
i tried to open a vidoe file and it* says "file loaded" and then "ERROR*
" *nothing plays.*

**Comment by ManbirJudge** [comment]
It was same with me. But I understood the code and there is no problem. It would show a white screen on startup. If you want to open a file you should press 'o' and an open file dialogue box will appear and you can choose any media file.

**Comment by Axel-Erfurt** [comment]
added a line to the README

**_press 'o' to open a video file or right mouse click for contextmenu_**

**Comment by m986883511** [comment]
I have same problem

(zimu-py3.9) PS D:\wang.chao\Nutstore\Project\Python\zimu\view-demo> python .\video1.py
QT5 Player started
press 'o' to open file (see context menu for more)
'gsettings' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
File loaded
DirectShowPlayerService::doRender: Unresolved error code 0x80040266 (IDispatch error #102)
Error:

**Comment by Axel-Erfurt** [comment]
Install K-Lite Codec Pack.
