### ISSUE TITLE
Pause/play function broken?

### ISSUE THREAD

**Issue by erikatbeof** [Axel-Erfurt/Python-QT-VideoPlayer#4]
Hi, and thanks for providing this code. I have been trying the video player in 'QT6_VideoPlayer.py' and got an issue that perhaps you can look into. 

Playing a video from command line works well, eg., 
```
python3 QT6_VideoPlayer.py video.mp4
```
However starting the video player and open a video with 'o',
```
python3 QT6_VideoPlayer.py
```
and then 'o'... The video is starting but the pause/play function is not working for me.

I'm using Ubuntu 22.04, and 

PyQt6==6.4.0
PyQt6-Qt6==6.4.0
PyQt6-sip==13.4.0

Best, Erik

**Comment by Axel-Erfurt** [comment]
I'm using LMDE5
PyQt6==6.4.0

pause/play works with button (press s to show/hide controls) and with space key

**Comment by erikatbeof** [comment]
Thanks for the reply! Ok, so you can not reproduce. Hm. Perhaps this is not an issue with your code. I tried another video file and the button mechanism is working well. Could be that the video I was trying is broken some how.

**Comment by erikatbeof** [comment]
I did some more testing and I still have problem with pause/play. Going from playing to pause, the 'clock'' is stopping and the Qt mediaplayer state is changed but the video is continuing to play. Press space a second time the video is stopped, for some time and then start again.

**Comment by Axel-Erfurt** [comment]
I tested it with Ubuntu 22.04 in Virtualbox and it works as it should.

**Comment by erikatbeof** [comment]
Thanks for the effort. I will try to do some more testing on my side.
